export const Recipes = [
  {
    id: 1,
    name: "Tarte aux pommes",
    image: "tarte",
    type: "dessert",
    tags: ["recettedemamie", "étudiant"],
    author: "Yoyo L'Asticot",
    nbPers: 4,
    nbVariable: false,
    diff: "Facile",
    note: 4.5,
    nbNote: 7,
    cooking: {
      prep: 10,
      bake: 40,
      bakeType: "Cookéo",
    },
    ingredients: [
      { name: "Sucre", quantity: "150", unity: "g" },
      { name: "Lait", quantity: "20", unity: "cl" },
      { name: "Farine", quantity: "200", unity: "g" },
      { name: "Lait", quantity: "20", unity: "cl" },
      { name: "Lait", quantity: "20", unity: "cl" },
      { name: "Avocat", quantity: "4", unity: "" },
    ],
    steps: [
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
    ],
    comment:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam quos at harum neque magni accusantium dolores molestiae voluptatibus.",
    comments: "",
  },
  {
    id: 2,
    name: "Risotto",
    image: "risotto",
    type: "dessert",
    tags: ["grandeoccasion", "impressionnant"],
    author: "Arthy Show",
    nbPers: 2,
    nbVariable: false,
    diff: "Difficile",
    note: 4.5,
    nbNote: 15,
    cooking: {
      prep: 15,
      bake: 20,
      bakeType: "Four",
    },
    ingredients: [
      { name: "Sucre", quantity: "150", unity: "g" },
      { name: "Lait", quantity: "20", unity: "cl" },
      { name: "Lait", quantity: "20", unity: "cl" },
      { name: "Lait", quantity: "20", unity: "cl" },
      { name: "Lait", quantity: "20", unity: "cl" },
      { name: "Avocat", quantity: "4", unity: "" },
    ],
    steps: [
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique et magnam consequatur delectus debitis.",
    ],
    comment:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam quos at harum neque magni accusantium dolores molestiae voluptatibus.",
    comments: "",
  },
];
