export const images = {
  nbpers: require("../../assets/images/nbpers.png").default,
  risotto: require("../../assets/images/risotto.png").default,
  tarte: require("../../assets/images/tarte.png").default,
  muesli: require("../../assets/images/muesli.png").default,
  friends: require("../../assets/images/friends.jpg").default,
  linkedin: require("../../assets/images/linkedin.png").default,
  mail: require("../../assets/images/mail.png").default,
  github: require("../../assets/images/github.png").default,
  recordit: require("../../assets/images/recordit.png").default,
  checklist: require("../../assets/images/checklist.png").default,
  default: require("../../assets/images/checklist.png").default,
  instagram: require("../../assets/images/instagram.png").default,
  facebook: require("../../assets/images/facebook.png").default,
  snapchat: require("../../assets/images/snapchat.png").default,
  tiktok: require("../../assets/images/tiktok.png").default,
  twitter: require("../../assets/images/twitter.png").default,
  whatsapp: require("../../assets/images/whatsapp.png").default,
};
